# Action name
name: CI

# Push rules
on:
  push:
    branches:
      - master

# This is where the magic happens
jobs:
  build_on_mac:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@master
      with:
        ref: master
    - uses: actions/setup-node@master
      with:
        node-version: 10.16
    - name: see directory
      run: ls
    - name: Install dependencies
      run: npm install
    - name: Build on MacOS
      env:
        ELECTRON: true
        APP_VERSION_NUMBER: 0.5.9
      run: npm run package-mac
    - name: see directory after building
      run: ls

  build_on_win:
    runs-on: windows-2016
    steps:
    - uses: actions/checkout@master
      with:
        ref: develop        
    - uses: actions/setup-node@master
      with:
        node-version: 10.16
    - name: see directory
      run: ls